- name: 详细错误诊断
  if: failure()
  run: |
    cd openwrt
    echo "=== 详细错误诊断 ==="
    
    echo "1. 检查包冲突:"
    grep -E "CONFIG_PACKAGE_(vsftpd|vsftpd-alt)" .config || echo "未找到 FTP 相关配置"
    
    echo ""
    echo "2. 查找其他可能的冲突:"
    find . -name "*.mk" -exec grep -l "conflict\|clash" {} \; | head -n 5
    
    echo ""
    echo "3. 检查编译日志中的错误:"
    grep -i "error\|conflict\|clash" build.log | tail -n 20
    
    echo ""
    echo "4. 检查已安装的包:"
    find staging_dir -name "*.install" -exec grep -l "vsftpd" {} \; | head -n 5
